
version: 1.0.{build}
shallow_clone: true

environment:
  matrix:
    - image: Visual Studio 2015
      GENERATOR: Visual Studio 14 2015
    - image: Visual Studio 2015
      GENERATOR: Visual Studio 14 2015 Win64
    - image: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017
    - image: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017 Win64

build:
  parallel: true

build_script:
  - cmd: echo "image:%APPVEYOR_BUILD_WORKER_IMAGE%"
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake --version
  - cmd: cmake -DBUILD_TEST=ON -DBUILD_SHARED_LIBS=OFF -G "%GENERATOR%" ..
  - cmd: cmake --build . --config "%CFG%"

test_script:
  - cmd: cd test && ctest -C "%CFG%" -V
  
