
version: 1.0.{build}
shallow_clone: true

image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - ARCH: 
    - ARCH: Win64

build:
  parallel: true

build_script:
  - cmd: |
      echo "image:%APPVEYOR_BUILD_WORKER_IMAGE%"
      echo "arch:%ARCH%, config:%CFG%"
      cmake --version
      mkdir build
      cd build
      set OPTS=-DBUILD_TEST=ON -DBUILD_SHARED_LIBS=OFF
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" cmake %OPTS% -G "Visual Studio 14 2015%ARCH%" ..
      if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" cmake %OPTS% -G "Visual Studio 15 2017%ARCH%" ..
      cmake --build . --config "%CFG%"

test_script:
  - cmd: cd test && ctest -C "%CFG%" -V
  
