os: Visual Studio 2015
platform: x64
shallow_clone: true
version: 1.0.{build}

# Matrix: GENERATOR, CFG

environment:
  matrix:
    - GENERATOR: Visual Studio 15 2017
    - GENERATOR: Visual Studio 15 2017 Win64
    - GENERATOR: Visual Studio 14 2015
    - GENERATOR: Visual Studio 14 2015 Win64

build:
  parallel: true

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DBUILD_TEST=ON -DBUILD_SHARED_LIBS=OFF -G "%GENERATOR%" ..
  - cmd: cmake --build . --config Debug
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cd test && ctest -C Debug -V
  - cmd: cd test && ctest -C Release -V

